### ISSUE TITLE
Object and function category testing require further planning

### ISSUE THREAD

**Issue by Moppa5** [Moppa5/COMP.SE.200-2020-assignment#1]
As the title points out tests for object and function category modules require further planning before the implementation starts. 

Object category includes modules
- get.js
- keys.js

Whereas function category
- reduce.js?
- memoize.js

Reduce is also marked for array category, thus we need to plan on which category it will eventually go.

**Comment by Moppa5** [comment]
Taken a look at reduce.js, I think it's wise to keep it on object category since it handles objects and returns some object data. It will be easier also when we can build the test cases in the same way, meaning that get.js and keys.js both take an object as parameter.

**Comment by HyperionCoding** [comment]
Reduce has been kept in array category as the tests fit well within the category.
